import os

ESSIM_CONTAINER_LIMIT = int(os.environ['ESSIM_CONTAINER_LIMIT'])
ESSIM_QUEUE_URL = os.environ['ESSIM_QUEUE_URL']
LOADFLOW_CONTAINER_LIMIT = int(os.environ['LOADFLOW_CONTAINER_LIMIT'])
LOADFLOW_QUEUE_URL = os.environ['LOADFLOW_QUEUE_URL']
ETM_CONTAINER_LIMIT = int(os.environ['ETM_CONTAINER_LIMIT'])
ETM_QUEUE_URL = os.environ['ETM_QUEUE_URL']
INIT_CONTAINER_LIMIT = int(os.environ['INIT_CONTAINER_LIMIT'])
INIT_QUEUE_URL = os.environ['INIT_QUEUE_URL']
ESDL_CONTAINER_LIMIT = int(os.environ['ESDL_CONTAINER_LIMIT'])
ESDL_QUEUE_URL = os.environ['ESDL_QUEUE_URL']
CONTAINER_SUBNET = os.environ['CONTAINER_SUBNET']
ESSIM_CONTAINER_SG = os.environ['ESSIM_CONTAINER_SG']
GENERAL_CONTAINER_SG = os.environ['GENERAL_CONTAINER_SG']