import os

INIT_QUEUE_URL = os.environ['INIT_QUEUE_URL']
ETM_QUEUE_URL = os.environ['ETM_QUEUE_URL']
ESSIM_QUEUE_URL = os.environ['ESSIM_QUEUE_URL']
ESDL_QUEUE_URL = os.environ['ESDL_QUEUE_URL']
ETM_REQUEST_LIMIT_PER_MINUTE = int(os.environ['ETM_REQUEST_LIMIT_PER_MINUTE'])
DATABASE_SECRET_NAME = os.environ['DATABASE_SECRET_NAME']
ENVIRONMENT = os.environ['ENVIRONMENT']
