import os

ENVIRONMENT = os.environ['ENVIRONMENT']
ESSIM_QUEUE_URL = os.environ['ESSIM_QUEUE_URL']
BUCKET_NAME = os.environ['BUCKET_NAME']
INFLUX_DB_IP = os.environ['INFLUX_DB_IP']
DATABASE_SECRET_NAME = os.environ['DATABASE_SECRET_NAME']
DATABASE_SCHEMA_NAME = os.environ['DATABASE_SCHEMA_NAME']

