import os

ENVIRONMENT = os.environ['ENVIRONMENT']
BUCKET_NAME = os.environ['BUCKET_NAME']
DATABASE_SECRET_NAME = os.environ['DATABASE_SECRET_NAME']
DATABASE_SCHEMA_NAME = os.environ['DATABASE_SCHEMA_NAME']
