import os

ENVIRONMENT = os.environ['ENVIRONMENT']
BUCKET_NAME = os.environ['BUCKET_NAME']
NETWORK_BUCKET_NAME = os.environ['NETWORK_BUCKET_NAME']
DATABASE_SECRET_NAME = os.environ['DATABASE_SECRET_NAME']
DATABASE_SCHEMA_NAME = os.environ['DATABASE_SCHEMA_NAME']
TENNET_LOADFLOW_QUEUE_URL = os.environ['TENNET_LOADFLOW_QUEUE_URL']
